### ISSUE TITLE
any plans for other sonoff devices?

### ISSUE THREAD

**Issue by ageorgios** [Andreaqc/Sonoff-ESP8266-HomeKit#3]
are there any plans for implementing other similar sonoff devices?

detailed instructions how to start off from a bare linux machine would be also very helpful

**Comment by peros550** [comment]
Very interesting question! I'd love to see support for the TH10/TH16.

**Comment by maccoylton** [comment]
Guys, the original library is deprecated, see announcement here:- https://github.com/HomeACcessoryKid/ESP8266-HomeKit/issues/41

the new library is here:- 
https://github.com/maximkulkin/esp-homekit

with examples here:- 
https://github.com/maximkulkin/esp-homekit-demo

**Comment by RavenSystem** [comment]
Here there are more Sonoff devices implementations, and it's based on esp-open-rtos and esp-homekit:
https://github.com/RavenSystem/esp-homekit-devices
