### ISSUE TITLE
GPIO14 - External button(wall switch)

### ISSUE THREAD

**Issue by osvaldoasn** [Andreaqc/Sonoff-ESP8266-HomeKit#4]
Hi, great work!
I'd like to know if is possible to use GPIO14 to change the status with a wall switch or a button?
Thanks.

**Comment by andreacucci** [comment]
Yes it is possible, GPIO14 seems to be not used on the Basic version.
You just need to set the right mode for GPIO14 and register an appropriate callback for it in the `relay` function, as i did for the other GPIOs.
