### ISSUE TITLE
WiFi config

### ISSUE THREAD

**Issue by RavenSystem** [Andreaqc/Sonoff-ESP8266-HomeKit#5]
Hello, 

Is it possible to change wifi configuration without reflashing?

Many thanks.

**Comment by andreacucci** [comment]
It is certainly possible, but you would need to code a new function to handle the wifi configuration at runtime.
It would be outside the HomeKit standard of course.

**Comment by RavenSystem** [comment]
Do you have any plan to implement it in the future?
