### ISSUE TITLE
How about to publish pre-compiled binaries?

### ISSUE THREAD

**Issue by i3laze** [Andreaqc/Sonoff-ESP8266-HomeKit#9]
Like Raven did:
https://github.com/RavenSystem/esp-homekit-devices/releases

**Comment by andreaem-it** [comment]
+1

**Comment by peros550** [comment]
+1 from me too!

**Comment by St0nehead** [comment]
+1 me too

**Comment by ageorgios** [comment]
have you seen this?
https://github.com/RavenSystem/esp-homekit-devices
